### ISSUE TITLE
Can you put a link the "Chinese" HTML labs? 

### ISSUE THREAD

**Issue by residentx10** [MicrosoftLearning/AZ-104ZH-MicrosoftAzureAdministrator#8]
Can you put a link to the Chinese HTML please? See images

![Chineselabs1](https://user-images.githubusercontent.com/9274020/146819846-806b9731-db3b-4125-9469-6d6b3bf439ed.png)
![Chineselabs2](https://user-images.githubusercontent.com/9274020/146819850-9d8369d4-fca9-49f5-aa78-d824cbc1574e.png)

**Comment by VietTran0302** [comment]
fixed
